version: '3.4'

services:
  portfolio:
    image: portfolio
    container_name: portfolio
    environment:
      - NODE_ENV=${NODE_ENV}
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000