version: '3.4'

services:
  portions-app-frontend:
    image: marvin-portfolio
    container_name: marvin-portfolio
    environment:
      - NODE_ENV=${NODE_ENV}
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000